config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }

    namespace :admin do
      resources :users do
        member do
          post :send_email
        end
      end
      resources :posts
    end

    # Fallback for unmatched routes
    match '*path', to: 'application#not_found', via: :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :user_permissions
  has_many :users, through: :user_permissions
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_paranoid
  has_many :posts, dependent: :destroy

  validates :name, presence:true
  validates :email, presence:true
  belongs_to :group
  has_many :user_permissions
  has_many :permissions, through: :user_permissions

  def self.admin_role
    User.instance_eval { @admin_context = true }
    yield
  ensure
    User.instance_eval { @admin_context = nil }
  end
end

app/models/user_permission.rb
class UserPermission < ApplicationRecord
  belongs_to :user
  belongs_to :permission
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_post, only: [:index,:new,:create,:show]
    after_action :verify_authorized
    def index
      # custome where exits
      # @posts = Post.where_assoc_exists(:user) do |user|
      #   user.where_assoc_exists(:user_permissions) do |user_permissions|
      #     user_permissions.where(permission_id: 1)
      #   end
      #     .or(
      #       user.where_assoc_exists(:group) do |group|
      #         group.where(name: 'Admin')
      #       end
      #     )
      # end.includes(:user)
      @posts = Post.where_assoc_exists(:user).includes(:user)
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      respond_to do |format|
        if @post.save
          format.html { redirect_to post_params, notice: 'Post was successfully created.' }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def show
      @post = Post.where(id: params[:id])
                  .where_assoc_exists(:user)
                  .includes(:user)
                  .first
    end

    private
      def post_params
        params.require(:post).permit(:title, :body, :user_id)
      end
      def authorize_post
        authorize Post
      end


  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]
    before_action :authenticate_user!

    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end

    # GET /users/1
    # GET /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)
      @user.password = '123456'
      User.admin_role do
        respond_to do |format|
          if @user.save
            format.html { redirect_to admin_users_path, notice: 'Client was successfully created.' }
            format.json { render :show, status: :created, location: @user }
          else
            format.html { render :new, status: :unprocessable_entity }
          end
        end
      end
    end


    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
      end
    end

    def send_email
      @user = User.find(params[:id])
      UserMailer.welcome_email(@user).deliver_later
      redirect_to admin_users_path, notice: 'Email sent!'
    end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        begin
          @user = User.find(params[:id])
        rescue ActiveRecord::RecordNotFound => e
          redirect_to '/404'
        end
      end

      def user_params
        params.require(:user).permit(:name, :email)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from Pundit::AuthorizationNotPerformedError, with: :handle_authorization_error

  def not_found
    render status: 404, file: 'public/404.html', layout: false
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
  end

  def after_sign_in_path_for(resource)
    if user_signed_in?
      admin_users_path
    else
      super
    end
  end
  private

  def user_not_authorized(exception)
    flash.now[:alert] = "You are not authorized to perform this action."

    render 'errors/unauthorized', status: :forbidden
  end
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/posts/index.html.erb
<h1>Posts List</h1>

<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Body</th>
    <th>User</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= post.user.name if post.user %></td>
      <td>
        <%= link_to 'Show', admin_post_path(post), class: 'btn btn-info btn-sm' %>
      <%= link_to 'Edit', edit_admin_post_path(post), class: 'btn btn-warning btn-sm' %>
        <%= link_to 'Destroy', admin_posts_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<!-- Thêm liên kết để tạo bài viết mới -->
<%= link_to 'New Post', new_admin_post_path, class: 'btn btn-primary' %>

app/views/admin/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post, url: admin_posts_path, html: { class: 'form-horizontal' } do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
    <% if @post.errors[:title].any? %>
      <div class="error-message">
        <%= @post.errors.full_messages_for(:title).first %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
    <% if @post.errors[:body].any? %>
      <div class="error-message">
        <%= @post.errors.full_messages_for(:body).first %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: 'Select a user', class: 'form-control' %>
    <% if @post.errors[:user_id].any? %>
      <div class="error-message">
        <%= @post.errors.full_messages_for(:user_id).first %>
      </div>
    <% end %>
  </div>
  <%= link_to "English", url_for(locale: 'en'), class: "dropdown-item" %>
 <%= link_to "Tiếng Việt", url_for(locale: 'vi'), class: "dropdown-item" %>


  <div class="actions">
    <%= form.submit 'Create Post', class: 'btn btn-primary' %>
  </div>

<% end %>

<%= link_to 'Back', admin_posts_path, class: 'btn btn-secondary' %>

app/views/admin/posts/show.html.erb
<h1>New Post</h1>

<%= form_with model: @post, url: admin_post_path do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: 'Select a user', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', admin_posts_path, class: 'btn btn-secondary' %>

app/views/admin/users/edit.html.erb
<%= form_with model: @user, url: admin_user_path do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
    <% if @user.errors[:name].any? %>
      <div class="error-message">
        <%= @user.errors[:name].first %>
      </div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control' %>
    <% if @user.errors[:email].any? %>
      <div class="error-message">
        <%= @user.errors[:email].first %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-primary' %>
  </div>

  <%= link_to 'Back', admin_users_path, class: 'btn btn-secondary' %>
<% end %>

app/views/admin/users/index.html.erb
<% content_for :title, "Users" %>
<h1>Users <%= @abc %></h1>
<%= link_to 'New User', new_admin_user_path, class: 'btn btn-primary mb-3' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', admin_user_path(user), class: 'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-warning' %></td>
        <td>
          <%= form_with url: admin_user_path(user), method: :delete, local: true, html: { class: 'd-inline' } do %>
            <%= button_to 'Delete', admin_user_path(user), method: :delete, class: 'btn btn-danger', form: { class: 'd-inline' } %>
          <% end %>
        </td>
        <td>
          <%= form_with url: send_email_admin_user_path(user), method: :post, local: true, html: { class: 'd-inline' } do %>
            <%= button_to 'Send mail', send_email_admin_user_path(user), method: :post, class: 'btn btn-info', form: { class: 'd-inline' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%= form_for @user, url: admin_users_path, html: { class: 'form-horizontal' } do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
    <% if @user.errors[:name].any? %>
      <div class="error-message">
        <%= @user.errors.full_messages_for(:name).first %>
      </div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control' %>
    <% if @user.errors[:email].any? %>
      <div class="error-message">
        <%= @user.errors.full_messages_for(:email).first %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'btn btn-primary' %>
  </div>

  <%= link_to 'Back', admin_users_path, class: 'btn btn-secondary' %>
<% end %>

app/views/admin/users/show.html.erb
<% content_for :title, "Show user" %>
<%= form_with model: @user, url: admin_user_path do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>
  <%= link_to 'Back', admin_users_path, class: 'btn btn-primary mb-3' %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MyApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to t('navbar.users'), admin_users_path, class: 'nav-link abcd' %>
        </li>
        <li class="nav-item">
          <% if policy(Post).index? %>
            <%= link_to t('navbar.posts'), admin_posts_path, class: 'nav-link' %>
          <% end %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= form_with url: destroy_user_session_path, method: :delete, class: 'nav-item' do |form| %>
              <%= form.submit t('navbar.logout'), class: 'btn btn-link nav-link' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || "MyApp" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_importmap_tags %>
  <meta name="turbo-prefetch" content="false">
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container mt-4">
  <% if (flash[:notice] && flash[:notice].length > 0) || (flash[:alert] && flash[:alert].length > 0) %>
    <div class="alert alert-<%= flash[:notice] ? 'success' : 'danger' %>">
      <%= flash[:notice] || flash[:alert] %>
    </div>
  <% end %>
  <%= yield %>
</div>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
</body>
</html>